project:
  type: website

website:
  title: "HUNTER INSIGHTS DASHBOARD"
  navbar:
    background: primary
    search: true
    left:
      - EconUpdate.qmd
      - housing.qmd
      - ../DashboardRefreshed/Multipliers/Multipliers.html
      
output:
  quarto::quarto_html:
    headings:
      - "NATIONAL CONDITIONS : Headlines"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

