project:
  type: website
  output-dir: ../../Dashboard/publish/
  resources: 
    - "*.html"

website:
  title: "HUNTER INSIGHTS DASHBOARD"
  navbar:
    background: primary
    search: true
    left:
      - text: "HOUSING INSIGHTS"
        file: healthyhousing.qmd
      - text: "GEOGRAPHY OF JOBS"
        file: GeogOfJobs.qmd
      - text: "ECONOMIC UPDATE"
        file: EconUpdate.qmd
      - text: "STRUCTURAL CHANGE"
        file: long_term.qmd
      - text: "HOUSING DASHBOARD"
        file: housing.qmd
      - text: "MULTIPLIERS"
        file: multipliers.qmd
      - text: "EMISSIONS"
        file: emissions.qmd
    
output:
  quarto::quarto_html:
    headings:
      - "NATIONAL CONDITIONS : Headlines"
    self_contained: true
    resource_dir: ../../Dashboard/publish/resources/


format:
  html:
    theme: pulse
    css: styles.css
    toc: true
  docx:
    toc:true

editor: visual

