```{=html}
<style>
    h3, h4, h5, h6 {
        color: darkblue;
        text-align: center;
    }
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      color: #333333;
      margin: 0;
      text-align: justify;
    }
    h1 {
      padding-top: 20px;
      border-top: 2px solid #444;
      color: darkblue;
      text-align: center;
    }
    h2 {
      padding-top: 40px;
      border-bottom: 2px solid #444;
      color: darkblue;
      text-align: center;
    }
</style>
```
# MULTIPLIERS


# Economic Multipliers in The Hunter Region

Understanding the role of multipliers is crucial in measuring the economic impact of industries in the region and uncovering the interconnections among different sectors.

## Output Multiplier

The output multiplier quantifies the ripple effects of increased output in a specific sector. When a particular industry in the Hunter Region experiences growth, it generates additional income and demand for goods and services, which in turn stimulates other sectors. The output multiplier provides insights into the overall economic output and the interconnectedness of industries within the region.


::: {style="display: flex; justify-content: center;"}
::: {style="flex: 1;"}
<!-- Embed the first figure here -->

<iframe src="../Dashboard_Working/Multipliers/figs/clustered_bar_Output_Multiplier.html" width="800" height="600">

</iframe>
:::
:::

The largest multiplier is for Electricity generation and distribution, which means this sector generates the most economic activity in the region. This relatively large value means that it has supply-chain links to other sectors in the region (such as coal mining). The smallest multiplier is for Clothing manufacturing, which reflects the fact that most clothing is imported into the region.

## Employment Multiplier 

The employment multiplier is a measure of the indirect and induced employment generated by a particular sector.

The multiplier is the ratio of direct plus indirect (plus induced if Type II multipliers are used) employment changes to the direct employment change. That is, if you know how much change in employment occurs in one industry, you can use the employment multiplier to calculate the change in employment for the whole region.

The total Employment effects show the direct plus indirect employment change relative to a unit increase in final use. That is, if an industry produces one more unit of final products, you can use the total employment effects to calculate the change in employment for the whole region.

These values are expressed in full-time equivalent or FTE. Total effects are per million AUD.


::: {style="display: flex; justify-content: center;"}
::: {style="flex: 1;"}
<!-- Embed the first figure here -->

<iframe src="../Dashboard_Working/Multipliers/figs/clustered_bar_Employment_jobs_Multiplier.html" width="800" height="600">

</iframe>
:::

::: {style="flex: 1;"}
<!-- Embed the second figure here -->

<iframe src="../Dashboard_Working/Multipliers/figs/clustered_bar_Employment_jobs_Total_Effect.html" width="800" height="600">

</iframe>
:::
:::

The multiplier for "Ownership of dwellings" is somewhat of an outlier as the direct employment stimulus in this sector is very small. Hence, when comparing the total effect to the direct effect, it produces a high multiplier.

The total supply chain effects of increasing production to final consumers by a million AUD (right figure above) shows the employment-intensive effects of the service sector.

## Income Multiplier 

The income multiplier measures the indirect and induced changes in income resulting from an initial injection of money into the economy. As money circulates through different sectors, it generates additional income for employees and business owners. In the Hunter Region, the income multiplier helps gauge the overall impact of economic activities on personal incomes and living standards.

The multiplier is the ratio of direct plus indirect incomes relative to the direct income change. That is, if you know how much change in income occurs in one industry, you can use the income multiplier to calculate the change in income for the whole region.

The total income effects show the direct plus indirect income change relative to a unit increase in final use. That is, if an industry produces one more unit of final products, you can use the total income effects to calculate the change in income for the whole region.

These values are expressed in million AUD. Total effects are per million AUD.


::: {style="display: flex; justify-content: center;"}
::: {style="flex: 1;"}
<!-- Embed the first figure here -->

<iframe src="../Dashboard_Working/Multipliers/figs/clustered_bar_Wages_Salaries_Multiplier.html" width="800" height="600">
</iframe>

<iframe src="../Dashboard_Working/Multipliers/figs/clustered_bar_Wages_Salaries_Total_Effect.html" width="800" height="600">
</iframe>

## Value added Multiplier 

The Value added (VA) multiplier is expressed as the ratio of the direct and indirect VA changes to the direct VA change. That is, if you have know the change in VA of a certain industry the VA multiplier can be used to calculate the change in VA for the whole region.

The total VA effect is expressed as the direct and indirect VA changes to the direct output change, due to a unit increase in final use. That is if you know the change in output for a certain industry the VA effect can be used to calculate the change in VA for the economy as a whole.



<iframe src="../Dashboard_Working/Multipliers/figs/clustered_bar_Value_added_Multiplier.html" width="800" height="600">
</iframe>

<iframe src="../Dashboard_Working/Multipliers/figs/clustered_bar_Value_added_Total_Effect.html" width="800" height="600">
</iframe>

---

For more information on theory behind multipliers, please see [NSW Treasury](https://www.treasury.nsw.gov.au/sites/default/files/2020-09/CEE%20IO%20User%20Guide%20-%20290920%20%28Web%20Final%29.pdf).


---
For more detail on the Hunter Insights Dashboard, please [contact IRF](IRF@newcastle.edu.au)